const APPS=[
{name:'Flourish',subtitle:'Affirmations · Wellbeing',appStoreId:'1613148062',appStoreUrl:'https://apps.apple.com/us/app/flourish-daily-affirmations/id1613148062',playStoreUrl:'https://play.google.com/store/apps/details?id=com.positivemindset.apps.flourish&pli=1',description:'Daily affirmations for positive thinking, self-worth, gratitude and emotional resilience.'},
{name:'QuoteUp',subtitle:'Motivation · Daily quotes',appStoreId:'1613717356',appStoreUrl:'https://apps.apple.com/us/app/quoteup-daily-motivation/id1613717356',description:'A focused daily motivation experience built around uplifting quotes and short moments of momentum.'},
{name:'MyVocab',subtitle:'Vocabulary · Learning',appStoreId:'1614457796',appStoreUrl:'https://apps.apple.com/us/app/myvocab-learn-new-words/id1614457796',description:'Short, repeatable sessions that help users expand vocabulary and retain new words.'},
{name:'Factly',subtitle:'Knowledge · Discovery',appStoreId:'1614132181',appStoreUrl:'https://apps.apple.com/us/app/factly-learn-something-new/id1614132181',description:'Interesting facts and useful knowledge delivered in a light, accessible format.'},
{name:'Jokio',subtitle:'Humor · Entertainment',appStoreId:'1615177330',appStoreUrl:'https://apps.apple.com/us/app/jokio-funny-jokes/id1615177330',description:'Quick entertainment through a simple stream of jokes and light everyday content.'},
{name:'Bliss',subtitle:'Meditation · Sleep',appStoreId:'6449584852',appStoreUrl:'https://apps.apple.com/us/app/bliss-meditation-sleep/id6449584852',description:'A minimalist meditation and sleep companion for relaxation, calm routines and recovery.'},
{name:'Nova',subtitle:'Microlearning · Daily growth',appStoreId:'6744055041',appStoreUrl:'https://apps.apple.com/us/app/nova-daily-microlearning/id6744055041',description:'Practical microlearning designed to fit personal development into everyday life.'}
];
const cache=new Map();function jsonp(url){return new Promise((resolve,reject)=>{const cb=`pm_${Math.random().toString(36).slice(2)}`,s=document.createElement('script'),t=setTimeout(()=>done(new Error('timeout')),10000);function done(err,data){clearTimeout(t);delete window[cb];s.remove();err?reject(err):resolve(data)}window[cb]=d=>done(null,d);s.onerror=()=>done(new Error('request failed'));s.src=`${url}${url.includes('?')?'&':'?'}callback=${cb}`;document.body.appendChild(s)})}
async function metadata(id){if(!cache.has(id))cache.set(id,jsonp(`https://itunes.apple.com/lookup?id=${id}&country=us`).then(d=>d?.results?.[0]||null));return cache.get(id)}
function storeLink(label,url){return `<a class="button button-secondary" href="${url}" target="_blank" rel="noopener noreferrer">${label}</a>`}
function screen(src,alt){return src?`<div class="screen"><img src="${src}" alt="${alt}" loading="lazy"></div>`:`<div class="screen"><div class="placeholder">Preview</div></div>`}
async function loadApp(app){try{const m=await metadata(app.appStoreId);return{...app,icon:m?.artworkUrl512||m?.artworkUrl100||'/logo.svg',screens:(m?.screenshotUrls||[]).slice(0,3)}}catch{return{...app,icon:'/logo.svg',screens:[]}}}
async function renderStudio(){const featured=document.querySelector('[data-studio-featured]'),compact=document.querySelector('[data-studio-compact]'),hero=document.querySelector('[data-hero-screens]');if(!featured&&!compact&&!hero)return;const data=await Promise.all(APPS.map(loadApp));const main=['Flourish','MyVocab','Nova'].map(n=>data.find(a=>a.name===n));if(hero){hero.innerHTML=main.map(a=>screen(a.screens[0],`${a.name} interface`)).join('')}if(featured){featured.innerHTML=main.map((a,i)=>`<article class="${i===0?'featured-project':'project-card'} reveal">${i===0?`<div><p class="project-label">Selected product</p><h3>${a.name}</h3><p>${a.description}</p><div class="store-links">${storeLink('App Store',a.appStoreUrl)}${a.playStoreUrl?storeLink('Google Play',a.playStoreUrl):''}</div></div><div class="screens">${[0,1,2].map(x=>screen(a.screens[x],`${a.name} screenshot ${x+1}`)).join('')}</div>`:`<div class="screens">${[0,1,2].map(x=>screen(a.screens[x],`${a.name} screenshot ${x+1}`)).join('')}</div><p class="project-label">Selected product</p><h3>${a.name}</h3><p>${a.description}</p><div class="store-links">${storeLink('App Store',a.appStoreUrl)}${a.playStoreUrl?storeLink('Google Play',a.playStoreUrl):''}</div>`}</article>`).join('')}
if(compact){const rest=data.filter(a=>!['Flourish','MyVocab','Nova'].includes(a.name));compact.innerHTML=rest.map(a=>`<a class="compact-app" href="${a.appStoreUrl}" target="_blank" rel="noopener noreferrer"><img src="${a.icon}" alt="${a.name} icon" loading="lazy"><span><strong>${a.name}</strong><small>${a.subtitle}</small></span><span class="text-link">App Store</span></a>`).join('')}window.observeReveals?.()}
async function renderCatalog(){const grid=document.querySelector('[data-app-catalog]');if(!grid)return;const data=await Promise.all(APPS.map(loadApp));grid.innerHTML=data.map(a=>`<article class="catalog-card reveal"><div class="catalog-head"><img src="${a.icon}" alt="${a.name} icon" loading="lazy"><div><p class="project-label">${a.subtitle}</p><h2>${a.name}</h2></div></div><p>${a.description}</p><div class="screens">${[0,1,2].map(x=>screen(a.screens[x],`${a.name} screenshot ${x+1}`)).join('')}</div><div class="store-links">${storeLink('App Store',a.appStoreUrl)}${a.playStoreUrl?storeLink('Google Play',a.playStoreUrl):''}</div></article>`).join('');window.observeReveals?.()}
renderStudio();renderCatalog();
